site:
    title: Your New PieCrust Website
    description: A sample website running with PieCrust
    author: Anonymous
    pretty_urls: true
    
smartypants:
    enable: true

baker:
    skip_patterns:
        - /^index.php/

